### ISSUE TITLE
Keep it Nord

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#10]
I know you'll give workbench theming after VS Code releases its API for it. This is not about it.

Mattia Astornio has its theme now for VS Code 
https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme
and Dracula has it too 
https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula

I want you to try out both the themes. 
And then reconsider about the color schemes provided here
https://github.com/arcticicestudio/nord-visual-studio-code/issues/8#issuecomment-292127716

Nord is made to be non-obstructive kind and that's what people love about it. Giving the above workbench theming will make it too obstructive. Please keep it minimal when you release. Thanks! 🙌

**Comment by arcticicestudio** [comment]
The styles posted in the linked comment have been made by a user of the theme, they won't be implemented like this 😉 
I'll try to adapt to the style of the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui) port project to keep it consistent over all UI port projects and adhere to the Nord style.

As soon as I start working on it there will be a PR everyone can test and post suggestions for improvements to preview the styles before it'll get merged.

**Comment by arcticicestudio** [comment]
The new workbench UI is now available as of the 🚢 shipped extension package release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.2.0).

**Comment by ajitid** [comment]
Thanks for informing! I was checking for it everyday... Downloading it straightaway now

**Comment by ajitid** [comment]
It's beautiful 😍
