### ISSUE TITLE
Babel compatibility

### ISSUE THREAD

**Issue by varog-norman** [arcticicestudio/nord-visual-studio-code#106]
Please make your theme more compatible with babel syntax plugins. 
For example http://i.imgur.com/eZe7ndc.png

**Comment by arcticicestudio** [comment]
Hi @varog-norman  :wave:, thanks for your contribution :+1: 
Sorry for the long delay, I've been really busy with my job, real life and [Nord's, finally launched, official website and documentation](https://www.nordtheme.com).

@mdogadailo submitted PR #114  to fix the problem. I've merged it to deploy it with the next release version :rocket:

**Comment by varog-norman** [comment]
@arcticicestudio, Thank you for your great job making such amazing things. I would like you to ask for one more thing: improve typescript syntax

**Comment by arcticicestudio** [comment]
Thanks, I've created a [note in the backlog board](https://github.com/arcticicestudio/nord-visual-studio-code/projects/2#card-19267142) that'll be converted into a new issue when I've checked al necessary scopes.
