### ISSUE TITLE
When not focused on sidebar, active file shows wrong color

### ISSUE THREAD

**Issue by octref** [arcticicestudio/nord-visual-studio-code#107]
![image](https://user-images.githubusercontent.com/4033249/52740889-ebd25a80-2f88-11e9-8a74-5699c7fe3201.png)

Now focus on editor, the active item becomes black.

![image](https://user-images.githubusercontent.com/4033249/52740936-0c9ab000-2f89-11e9-86f6-b291f9c79bc7.png)

I would expect the color to stay the same.

**Comment by octref** [comment]
This can be fixed by using the value of `list.focusBackground` for `list.inactiveFocusBackground` (seems to be a new key).

Here's what I'm using:

```json
{
  "workbench.colorCustomizations": {
    "[Nord]": {
      "list.inactiveFocusBackground": "#88c0d099",
    }
  }
}
```

**Comment by arcticicestudio** [comment]
Hi @octref :wave:, thanks for your report :+1: 

The missing key is unfortunately due to the last supported VS Code version this theme was built for. I'm really not feeling well leaving the project is such an outdated state, but the hard work on the official Nord docs coming closer to the initial launch which also means that I can finally spend time again to process these 300+ issues in all port projects :rofl: 

Also thanks for posting a workaround that users can add to their settings to support the missing key in the mean time.

**Comment by octref** [comment]
No worries, that's a lot of work. Good luck!

If there's anything I can help (or VS Code can do to help), let me know.

**Comment by arcticicestudio** [comment]
@octref Sorry for the long delay, I've been busy with [finally launching Nord's official website and documentation](https://www.nordtheme.com) :rocket: 

I've submitted PR #116  to add the new theme key, but used `nord2` with a opacity of 80% instead to match the style of inactive list items that were focused without the keyboard (`list.inactiveSelectionBackground`).

**Comment by octref** [comment]
Thanks, the PR looks fine to me. Congrats on launching the website, it looks amazing!

Just a small suggestion, would be great if these icons become clickable links:

![image](https://user-images.githubusercontent.com/4033249/54883724-ef79bc80-4e25-11e9-846e-c8304078d342.png)

**Comment by arcticicestudio** [comment]
Thanks, it took me a long time and many hours of torment my creative brain cells to decide how to design and architecture the site :smile: 

Yeah it would be nice if these can be clicked to make it faster for users to get to the port specific landing page. Maybe I'll check if the SVGs [`<a>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a) works for it. Currently the logos are divided into 3 SVG layers that are animated with a different momentum to achieve a depth effect. There was no reason to animate each logo individually but getting less performance so the `<a>` element might be a nice solution, even if this is kind of "hardcoded" URLs in the image ^-^
