### ISSUE TITLE
Do not highlight function arguments in Python

### ISSUE THREAD

**Issue by Al2Me6** [arcticicestudio/nord-visual-studio-code#108]
I feel like arguments to functions should not be colored (especially with the same color as the function itself!), as this can lead to confusion.

For example, here's some code to demonstrate the issue:

![image](https://user-images.githubusercontent.com/35266431/53140164-df866880-3559-11e9-834b-46f5d0e26f03.png)

At a glance, it is unclear that `prev_x` is a variable while `babylon()` is a function.

**Comment by Al2Me6** [comment]
I have found the fix to the problem... removing `"source.python meta.function-call"` from line 1004 in `/themes/nord.json`.

If you would like I can submit a PR sometime this weekend.

**Comment by arcticicestudio** [comment]
@Al2Me6 Sorry for the long stale state.

Thanks again for your report and fix :+1:
It works fine so I've created PR #113 to get this into the next release version.
