### ISSUE TITLE
Line separating code area and side bar

### ISSUE THREAD

**Issue by krupenja** [arcticicestudio/nord-visual-studio-code#121]
Thank you for this amazing theme!

Is there a way to completely disable the thin light line separating code area and side bar?

![image](https://user-images.githubusercontent.com/26354715/56756586-c0df6080-679a-11e9-9e2b-628fb107c88b.png)

**Comment by arcticicestudio** [comment]
Hi @krupenja :wave:, nice to see you like the theme.

The sidebar border can be styled by adding the following _workbench_ customization to your settings:

```json
"workbench.colorCustomizations": {
  "[Nord]": {
    "sideBar.border": "#2e3440"
  }
}
```

This will use `nord0` as color that is also used as base editor and sidebar background, but you can change it to whatever you like. Also by appending a alpha channel at the end of the HEX color code you can adjust the opacity of the color, so e.g. by appending `00` the used color will be completely transparent.

**Comment by krupenja** [comment]
That works! Thank you for the fast reply!
