### ISSUE TITLE
Code info can be covered by scroll bar

### ISSUE THREAD

**Issue by Phlicess** [arcticicestudio/nord-visual-studio-code#13]
![image](https://cloud.githubusercontent.com/assets/11753644/25789819/479dc926-33e6-11e7-87de-0896f0708a6d.png)
![image](https://cloud.githubusercontent.com/assets/11753644/25789855/a6ec54ce-33e6-11e7-9877-cbc730706727.png)

**Comment by Phlicess** [comment]
Hoping fix the bug : )

**Comment by arcticicestudio** [comment]
<p align="center"><strong>Preview</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/26023389/a75879d8-37ba-11e7-8c1b-c5ee6020db1c.png"/><br><strong>Hovered</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/26023391/b64e6074-37ba-11e7-8b8b-210e6056d029.png"/></p>

**Comment by arcticicestudio** [comment]
Thanks for the report 👍 
I've already pushed a fix which will be merged into the next release version.

**Comment by neilsustc** [comment]
So it's not released now?

**Comment by arcticicestudio** [comment]
@neilsustc Sorry, I've been busy. I'll try to deploy it on the weekend.

**Comment by nomenon** [comment]
?

**Comment by arcticicestudio** [comment]
Sorry for the delay!
🚢 Finally shipped with extension release version 🏷 [0.3.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.3.0).

Closes #22

/cc @Phlicess @isidorn @Livven @GreatDanton @ajitid @neilsustc @nomenon
