### ISSUE TITLE
Font in screenshots?

### ISSUE THREAD

**Issue by josh-byster** [arcticicestudio/nord-visual-studio-code#149]
Hi,

What is the font and settings for the font (weight, etc.) that is used in the README images ([example](https://raw.githubusercontent.com/arcticicestudio/nord-docs/develop/assets/images/ports/visual-studio-code/ui-overview-go.png))? It may be nice to have that listed somewhere on the README so one can design their VS Code to look exactly like what the picture shows.

**Comment by arcticicestudio** [comment]
Hi @josh-byster, the font of the source code (editor) is the awesome [Source Code Pro][scp] font and the UI uses the system default font of macOS Mojave. On my main (Arch) Linux system I use the absolute clean [Inter UI][i] font.
Some great UI font alternatives are [Roboto][r], [Rubik][ru] or [Nunito Sans][n] while an alternative for the editor might be [Hack][h], a font type that has also been especially developed for source code and is similar to _Source Code Pro_, but comes with some more monotype styles as well as additional character features.

I've planned to document things like this in the documentation of the project on the website in FAQ

[scp]: https://fonts.google.com/specimen/Source+Code+Pro
[r]: https://fonts.google.com/specimen/Roboto
[ru]: https://fonts.google.com/specimen/Rubik
[n]: https://fonts.google.com/specimen/Nunito+Sans
[i]: https://rsms.me/inter
