### ISSUE TITLE
Set `textCodeBlock.background`

### ISSUE THREAD

**Issue by octref** [arcticicestudio/nord-visual-studio-code#155]
By not setting `textCodeBlock.background` hover/completion could look like this for inline code blocks:

![image](https://user-images.githubusercontent.com/4033249/64992284-6c8f6700-d888-11e9-93df-bcc51025f551.png)

![image](https://user-images.githubusercontent.com/4033249/64992295-72854800-d888-11e9-86f0-d2cf30b3a1c0.png)

I suggest adding a light background.

You can test this example by opening https://github.com/microsoft/vscode-custom-data/tree/master/samples/helloworld, opening `test.html` and hover on `my-button`.

**Comment by arcticicestudio** [comment]
Hi @octref :wave:, thanks for your contribution :+1:

I've submitted #158 that adds the theme key using `nord3` as brighter background color compared to the default color.
