### ISSUE TITLE
File icons used on screenshot?

### ISSUE THREAD

**Issue by francisceril** [arcticicestudio/nord-visual-studio-code#157]
The title says it. Interested in what file icons used on the screenshot?
Thanks.

**Comment by arcticicestudio** [comment]
The icons used for the screenshot is the [Material Theme Icons][old] extension (by  [Mattia Astorino][olda]), but in one of the later versions they changed the style so I've switched to [Material Icon Theme][new] (by [Philipp Kief][newa]) by for my personal setup. The new extension provides many customizations options to adjust the icons to match Nord's style. The screenshot will also be updated later on to use the new icons theme.

You can find the configurations of the new extension in [my personal _.dotfile_ repository][dots].

Also see [this Reddit post][r] in the official _Nord_ subreddit. 

[old]: https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons
[olda]: https://marketplace.visualstudio.com/publishers/Equinusocio
[new]: https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme
[newa]: https://marketplace.visualstudio.com/publishers/PKief
[dots]: https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/visual-studio-code/settings.json#L207-L211
[r]: https://www.reddit.com/r/nordtheme/comments/d2f6m4/does_anybody_know_how_to_modify_the_ui_of_vscode
