### ISSUE TITLE
JS parentheses in string templates use string color

### ISSUE THREAD

**Issue by kufii** [arcticicestudio/nord-visual-studio-code#162]
![photo_2019-10-08_13-19-35](https://user-images.githubusercontent.com/4913552/66418309-cee30f80-e9cf-11e9-9318-26524e59310b.jpg)

See the parens on line 6?

I did the following workaround in my settings.json to fix it

```javascript
{
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "meta.embedded.line.js meta.brace.square.js",
          "meta.embedded.line.js meta.brace.round.js"
        ],
        "settings": {
          "foreground": "#eceff4"
        }
      }
    ]
  }
}
```

**Comment by arcticicestudio** [comment]
Hi @kufii :wave:, thanks for your contribution :+1:
I'll reproduce the problem and merge your changes when it works fine. Or if you'd like to submit a PR feel free to do so, maybe you're attending at [Hacktoberfest][h].

[h]: https://hacktoberfest.digitalocean.com/

**Comment by kufii** [comment]
PR submitted!

**Comment by krupenja** [comment]
Off-topic: I was wondering which font are you using in that screenshot?

**Comment by kufii** [comment]
It's operator mono with [ligatures](https://github.com/kiliman/operator-mono-lig)

**Comment by krupenja** [comment]
Thanks!

**Comment by svipas** [comment]
This is already fixed in [this PR](https://github.com/arcticicestudio/nord-visual-studio-code/pull/142) with more fixes for JS & TS.
