### ISSUE TITLE
Elixir: Missing syntax highlight in modules and atoms 

### ISSUE THREAD

**Issue by feliperenan** [arcticicestudio/nord-visual-studio-code#165]
You can see the issue on the screenshot below:

![image](https://user-images.githubusercontent.com/27698968/68952863-54c15a00-07c9-11ea-93d7-017e3db4fa37.png)

I've done this workaround on my current settings. But I'm not sure if they should be in this repo or somewhere else though since scopes come from [vscode-elixir-ls](https://github.com/JakeBecker/vscode-elixir-ls/blob/master/syntaxes/elixir.json)

```
  "editor.tokenColorCustomizations": {
    "[Nord]": {
      "types": "#8FBCBB",
      "textMateRules": [
        {
         "name": "Elixir: module attributes",
         "scope": "variable.other.readwrite.module.elixir",
         "settings": {
           "foreground": "#D8DEE9",
           "fontStyle": "bold"
         }
        },
        {
         "name": "Elixir: atoms",
         "scope": "constant.other.symbol.elixir",
         "settings": {
           "foreground": "#D8DEE9",
           "fontStyle": "bold"
         }
        },
        {
         "name": "Elixir: modules",
         "scope": "variable.other.constant.elixir",
         "settings": {
           "foreground": "#8FBCBB",
         }
        },
      ]
    }
  }
```
Then got this result:
![image](https://user-images.githubusercontent.com/27698968/68952827-43784d80-07c9-11ea-9487-879b8e60e79f.png)

**Comment by frfroes** [comment]
+1 for this. 
The workaround works like a charm, thanks @feliperenan ! Still, It would be better to have it out of the box, anyway.

**Comment by arcticicestudio** [comment]
Hi @feliperenan :wave:, thanks for your contribution :+1:
Adding explicit support for popular language extensions that provide enhanced highlighting compared to the bundled/builtin syntax extensions is totally fine, but I guess we should use the [origin extensions instead of the fork you've linked][ext] to ensure to cover most users.

I've added it to the backlog, but feel free to submit a PR if you like :smile: 

[ext]: https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls

**Comment by feliperenan** [comment]
@arcticicestudio thanks for the reply. I didn't realize I linked a file from a fork :see_no_evil: . Anyway, I double checked and there is no change from the original repository. :raised_hands:

Also, I took the opportunity to send the pull-request and I would appreciate your reviews :pray:. Please, let me know if there is something to improve there :wink: 

Thanks :wave:
