### ISSUE TITLE
Better support for Rust syntax highlight

### ISSUE THREAD

**Issue by ashrithr** [arcticicestudio/nord-visual-studio-code#167]
Rust syntax highlighting is not as good as nord-vim (fixed in https://github.com/arcticicestudio/nord-vim/issues/138). It would be great to add similar support to vscode as well.

**Comment by arcticicestudio** [comment]
Hi @ashrithr :wave:, thanks for your contribution :+1:
I've added it to the backlog, but feel free to submit a PR if you like.

**Comment by iipom** [comment]
I tried my hand at doing this today, but it's a lot more confusing than I expected. This is easily my favourite theme and not having Rust support is kinda a let down. Hope someone can get around to this soon 🙏

**Comment by tobiasmoldan** [comment]
Found this theme earlier and I really like it so far, but had to add some overwrites to my own config to make it more pleasing with rust.

```json
    "editor.semanticTokenColorCustomizations": {
        "[Nord]": {
            "enabled": true,
            "rules": {
                "interface:rust": "#8FBCBB",
                "enum:rust": "#8FBCBB",
                "enumMember:rust": "#8FBCBB",
                "struct:rust": "#8FBCBB",
                "keyword:rust": {
                    "foreground": "#81A1C1",
                    "italic": true
                },
                "namespace:rust": "#8FBCBB",
                "typeParameter:rust": "#8FBCBB"
            }
        }
    }
```

![image](https://user-images.githubusercontent.com/16738368/109532638-9b6bbe00-7ab9-11eb-86c7-8665e2953cff.png)

Don't really have the time or energy right now to create a pr but maybe someone (@iipom) finds this useful.

**Comment by vhladko** [comment]
Hey there, I've just created a PR for this issue. Inspired by vim version and some Typescript rules from vscode. If you have a minute, could you pls review it ?

https://github.com/arcticicestudio/nord-visual-studio-code/pull/240
