### ISSUE TITLE
Windows terminal

### ISSUE THREAD

**Issue by Z4RX** [arcticicestudio/nord-visual-studio-code#170]
Change pls the colors of commands which start from - and --. Now it s really difficult to read them.
Here is a screenshot: 
![image](https://user-images.githubusercontent.com/58516282/76627977-0ccefb80-654d-11ea-817a-dd8a883143ed.png)

**Comment by arcticicestudio** [comment]
Hi @Z4RX :wave:, thanks for your contribution :+1:
