### ISSUE TITLE
General theme improvements to keep an eye on

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#18]
Please add these color customisations to your theme when they are made available
https://github.com/Microsoft/vscode/issues/25966

**Comment by arcticicestudio** [comment]
Thanks for the note, I've added a card to the project board 😄

**Comment by ajitid** [comment]
Closed the issue and added documentation label, what does that mean?

**Comment by arcticicestudio** [comment]
It means that I've added [this] card to the project board. It'll be converted to a issue as soon as the feature it tracks gets merged into VS Code so it can be adapted to the theme.
