### ISSUE TITLE
Why is 0.15 not published in the VS Marketplace?

### ISSUE THREAD

**Issue by J0F3** [arcticicestudio/nord-visual-studio-code#184]
Hi there,

Just a short question. Just noticed that the 0.15 is not in the marketplace. (only 0.14)
Has this a specific reason? 

Thanks!

**Comment by arcticicestudio** [comment]
Hi @J0F3, thanks for reporting 👍🏼 
The reason is simple: I forgot to push it to the registry 😆 
Creating the GitHub Action to automatically deploy it is still on the TODO list for this repository.

Anyway, it's deployed now and should be available from the marketplace & IDE within the next minutes.
