### ISSUE TITLE
Class Name, Var name not getting highlighted in doc comments

### ISSUE THREAD

**Issue by GJJ2019** [arcticicestudio/nord-visual-studio-code#185]
This is current screen of vs-code with doc comment (in dart)

![Screenshot (129)](https://user-images.githubusercontent.com/45948168/97980695-36e46f00-1df7-11eb-9526-d74f2272c87e.png)

**How it should be** 

This is screen from intellij ide with doc comments highlighted

![Screenshot (130)](https://user-images.githubusercontent.com/45948168/97980883-7ad77400-1df7-11eb-91b4-645c7cc1d87f.png)

**Comment by arcticicestudio** [comment]
Hi @GJJ2019 👋🏼 , thanks for your contribution :+1:

Can you please check which scope is used for these elements using the [builtin scope inspector][si]?

[si]: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

**Comment by GJJ2019** [comment]
language | dart
-- | --
standard token type | Comment
foreground | #616E88
background | #2E3440
contrast ratio | 2.43

![Screenshot (136)](https://user-images.githubusercontent.com/45948168/101988371-2c9f7580-3cbf-11eb-86fe-69638f13b4ab.png)

**Comment by arcticicestudio** [comment]
Has the Dart syntax highlighting been improved for comments in recent versions or is this still a problem? Like you've posted the token type that gets applied is `Comment` which is the base group for comments. As long as the syntax parser is not able to detect special elements like class names it is also not possible to adapt it to Nord.

**Comment by GJJ2019** [comment]
Yep, its showing now. Thx & Kudos.
