### ISSUE TITLE
Text color issue of Nord theme in extensions of VS Code

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#19]
![drac](https://cloud.githubusercontent.com/assets/26769888/26066803/c37d57a8-39b5-11e7-8a13-61f6932a87e7.gif)
VS Code: 1.12.1
OS: Windows 10

**Comment by arcticicestudio** [comment]
This is a side effect of the [logo](https://github.com/arcticicestudio/nord-visual-studio-code/blob/develop/assets/nord-visual-studio-code-banner.svg) which is colorized the same as the main background color. I've designed it to fit well to the GitHub README rendering.

![ghi-19-scrot-github-readme](https://cloud.githubusercontent.com/assets/7836623/26070310/7843cd50-39a4-11e7-9a04-bd3ddc1c948e.png)
