### ISSUE TITLE
What is the icon theme showen?

### ISSUE THREAD

**Issue by Ryan-da-ghost** [arcticicestudio/nord-visual-studio-code#191]
shown*

**Comment by arcticicestudio** [comment]
Hi @Ryan-da-ghost 👋🏼 
Actually the screenshot is a bit outdated. I've switched to another theme, you can find the details in my _.dotfile_  repository within issue https://github.com/arcticicestudio/igloo/issues/196. There's also a [small conversation on Twitter about this topic][tw].

[tw]: https://twitter.com/tibotiber/status/1258971420945575937
