### ISSUE TITLE
Color of Selected Search Text Same as BG in Quick Open

### ISSUE THREAD

**Issue by jacobgraf** [arcticicestudio/nord-visual-studio-code#196]
### Expected Behavior

When I search for a file using Quick Open (CMD-P) I should be able to easily read the selected item.

### Actual Behavior

The search term in the selected item is the same color as the background of the selected item so you can't easily read it.

## Example

![CleanShot 2021-05-30 at 09 50 47@2x](https://user-images.githubusercontent.com/146333/120109029-504f5e80-c12d-11eb-9c5d-5e6bbda98f5c.jpg)

## Environment and Versions

- What is the version of _Nord Visual Studio Code_ you are running?

0.15.1

- What is the name and the version of your OS?

macOS Big Sur 11.3.1

- What is the name and the version of VS Code you are running?

Version: 1.57.0-insider
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T10:00:38.762Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0

**Comment by RYDB3RG** [comment]
same with:

```
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z (1 day ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

I guess its caused by [Updated Quick Pick & suggest widget colors](https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors)
overwriting the new values in settings.json workarounds the issue for me:
```json

        "workbench.colorCustomizations": {
            "list.focusHighlightForeground": "#fff",
            "quickInputList.focusForeground": "#fff",
            "editorSuggestWidget.selectedForeground":"#fff",
        },
```

**Comment by ad-on-is** [comment]
> same with:
> 
> ```
> Version: 1.57.0 (user setup)
> Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
> Date: 2021-06-09T17:18:42.354Z (1 day ago)
> Electron: 12.0.9
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Windows_NT x64 10.0.19043
> ```
> 
> I guess its caused by [Updated Quick Pick & suggest widget colors](https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors)
> overwriting the new values in settings.json workarounds the issue for me:
> 
> ```json
>         "workbench.colorCustomizations": {
>             "list.focusHighlightForeground": "#fff",
>             "quickInputList.focusForeground": "#fff",
>             "editorSuggestWidget.selectedForeground":"#fff",
>         },
> ```

I prefer "#000" since it's less strian on the eyes.

**Comment by jacobgraf** [comment]
I found these to work quite well depending on your taste...

**Light:**

```json
"workbench.colorCustomizations": {
    "list.focusHighlightForeground": "#f1f9fa",
    "quickInputList.focusForeground": "#f1f9fa",
    "editorSuggestWidget.selectedForeground":"#f1f9fa",
},
```


**Dark:**

```json
"workbench.colorCustomizations": {
    "list.focusHighlightForeground": "#3c6169",
    "quickInputList.focusForeground": "#3c6169",
    "editorSuggestWidget.selectedForeground":"#3c6169",
},
```

**Comment by pspeter3** [comment]
That looks great! Is it possible to make that the official solution? Right now the contrast is making the theme hard to use.

**Comment by arcticicestudio** [comment]
Hi @jacobgraf, @RYDB3RG, @ad-on-is and @pspeter3 :wave:, thanks for your contributions :+1:
The latest VS Code version 1.57.0 “broke“ the styles through the introduction of more fine grained theme keys. I've pulled some app updates today and was also facing the problem, but like always the OSS community has been quicker 😉 

I've been going through the release notes of VS Code version `1.45.0` up to `1.57.0` to get up-to-date with theme/style specific changes. I hope I can adapt these and ship a new release version as soon as possible.
@jacobgraf The suggestion looks nice, I've also played around with the new keys and using `nord4` to `nord6` for the “lazy match“ tokens should work best, but I'm not sure about the background accent color yet.

**Comment by arcticicestudio** [comment]
To get this inconsistency fixed as soon as possible and make the theme better usable again I've changed the plan for the next version `0.16.0` and submitted #199. Using `nord6` as highlight color for the quick picker should work fine with the `nord8` background, also mainly because the color for non-focused entries still uses `nord8`.
Let me know what you think about it, I'm happy for every feedback.
