### ISSUE TITLE
Color intellisense more

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#20]
Can't this be colored?

![untitled](https://cloud.githubusercontent.com/assets/26769888/26271936/8ccc9eda-3d2a-11e7-83ad-f95d2af383ff.png)

**Comment by ajitid** [comment]
https://github.com/Microsoft/vscode/issues/26671
this is implemented with different keys

**Comment by arcticicestudio** [comment]
This should already work out-of-the-box. The selectors `editorHoverWidget.border` and `editorHoverWidget.background` are included in the latest release version using `nord1` as value.

**Comment by ajitid** [comment]
It wasn't working the day I put this issue. At that time there was 0.2.0 release. If it is already implemented, then close this issue.

**Comment by arcticicestudio** [comment]
Sorry for the late reply, had no time to work on private projects some months. I've announced it on Twitter, but there was no way to inform all contributors in all port projects.
Anyway, it's available in version 0.3.0 so I'll remove it from the version 0.4.0 project board and milestone and add it to the corresponding closed board and milestone.
