### ISSUE TITLE
Bracket color in VSCode 1.60

### ISSUE THREAD

**Issue by roosephu** [arcticicestudio/nord-visual-studio-code#225]
The most recent update to VSCode brings a new feature, which [colorizes brackets fast and also allows customization](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization). Is it possible to incorporate the feature with the wonderful Nord theme? Thanks!

**Comment by arcticicestudio** [comment]
Hi @roosephu :wave:, thanks for your contribution :+1:
The new color tokens will be added to Nord, but please note that bracket pair colorization is a feature that does not go well with the design concepts of Nord and the recommendation is therefore to not enable it. Of course this is always a personal preference and the feature be used as you wish, but note that the bracket colors defined by the Nord theme won't be changed on request but users can [simply customize it on their own][1].

[1]: https://www.nordtheme.com/docs/ports/visual-studio-code/customization
