### ISSUE TITLE
Php variables

### ISSUE THREAD

**Issue by sluchznak** [arcticicestudio/nord-visual-studio-code#23]
Hello. I don't know is bug or not.
![image](https://cloud.githubusercontent.com/assets/4091442/26824711/42abedd0-4ad4-11e7-86c5-7bc1290b3881.png)

**Comment by arcticicestudio** [comment]
Sorry, but I need more information. What' the exact problem, everything is colorized the way it should be on the screenshot.

**Comment by arcticicestudio** [comment]
Closing this for now due to missing information and stale status.

@sluchznak  Feel free to open it again or post a more detailed description what the issue might be so I can investigate :smile:
