### ISSUE TITLE
Published on Open VSX extension is outdated

### ISSUE THREAD

**Issue by pajecawav** [arcticicestudio/nord-visual-studio-code#238]
Hi. I had the same problem as #237 and then I noticed that [Open VSX extension](https://open-vsx.org/extension/arcticicestudio/nord-visual-studio-code) still uses version 0.15.0 which was released _1.5 years ago_. Any chance on publishing the latest version to Open VSX?

**Comment by IceWreck** [comment]
Same. I came here to complain about #237 and saw this.

**Comment by svengreb** [comment]
Thanks for your patience, time was limited again. The (currently) [latest version 0.19.0][1] has been pushed to the Open VSX registry some minutes ago and [is available now][2]. 

[1]: https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.19.0
[2]: https://open-vsx.org/extension/arcticicestudio/nord-visual-studio-code/0.19.0
