### ISSUE TITLE
bracket pair colorization is hard to tell apart

### ISSUE THREAD

**Issue by bayuprathama** [arcticicestudio/nord-visual-studio-code#239]
since VSCode already implemented native bracket pair colorization and it's likely match the color of the theme, for me it's a little bit hard to tell one and another opening/closing brackets. maybe using Nord aurora color palette will result a better contrast

the og bracket colorization
![bracket](https://user-images.githubusercontent.com/95031345/146006409-70bd503b-6da5-4a0e-af45-b45e62753a01.png)

using custom aurora color palette in the config
![aurora](https://user-images.githubusercontent.com/95031345/146007570-0ac0885f-14a3-440e-9c7c-49a31c51a014.png)

**Comment by NatoBoram** [comment]
Oh shoot, I didn't even notice they were colourized!

Using https://www.nordtheme.com/docs/colors-and-palettes#aurora, here's how you can define your own colours.

```json
{
  "workbench.colorCustomizations": {
    "[Nord]": {
      "editorBracketHighlight.foreground1": "#B48EAD",
      "editorBracketHighlight.foreground2": "#A3BE8C",
      "editorBracketHighlight.foreground3": "#EBCB8B",
      "editorBracketHighlight.foreground4": "#D08770",
      "editorBracketHighlight.foreground5": "#BF616A",
      "editorBracketHighlight.unexpectedBracket.foreground": "#BF616A"
    }
  }
}
```

If you want to use the [original extension](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2#settings)'s colours, they were `Gold`, `Orchid` and `LightSkyBlue`, which are [HTML colour names](https://www.w3schools.com/colors/colors_names.asp).

**Comment by svengreb** [comment]
Hi @bayuprathama :wave:

As @NatoBoram already explained you can simply customize the bracket style on your own for yourself.
Also please see #231 that includes a summary about how Nord handled the adaption of this feature and that the current style is by design. It won't be changed for all users but instead everyone can personalize it to match their preferences.
