### ISSUE TITLE
More theme improvements

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#24]
- [Color of editor squiggles](https://github.com/Microsoft/vscode/pull/27053)
- [Selection color within workbench](https://github.com/Microsoft/vscode/pull/26093)
- Progress bar coloring with `"progressBar.background"`
- Changing button color for Install with `"extensionButton."`

#### Colors of these can also be changed

![screenshot 105](https://user-images.githubusercontent.com/26769888/27015516-c697577c-4f2c-11e7-874c-6d0250aa0db5.png)
- BG/FG color of that Total 494 settings: colored with `"badge.background"` and `"badge.foreground"`
- Line below User Settings
------------------------

![screenshot 104](https://user-images.githubusercontent.com/26769888/27015520-ea1cae2c-4f2c-11e7-8cbc-4b59cc41ecf4.png)
- Color of the seperator (between Monokai Dimmed and Install Additional Color Themes)

**Comment by ajitid** [comment]
And please update the color of comments to look more legible.
I'm asking for a temporary fix.

**Comment by arcticicestudio** [comment]
Thanks for this summary of new workbench features :+1: 

## Tasks
### Workbench
#### [Base Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_base-colors)
  - [ ] `selection.background`

#### [Progress Bar](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_progress-bar)
  - [ ] `progressBar.background`

#### [Extensions](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_extensions)
  - [ ] `extensionButton.prominentForeground`
  - [ ] `extensionButton.prominentBackground`
  - [ ] `extensionButton.prominentHoverBackground`

### [Editor](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors)
#### Errors and Warnings
  - [ ] `editorError.foreground`
  - [ ] `editorError.border`
  - [ ] `editorWarning.foreground`
  - [ ] `editorWarning.border`

**Comment by ajitid** [comment]
Maybe this line below User Settings isn't cutomisable...

![capture](https://user-images.githubusercontent.com/26769888/27510349-0d265400-592c-11e7-97cf-a39f46a4d25c.PNG)



> Determine whether the separator line of the command bar is customizable.

But this one is though:

![screenshot 154 _li](https://user-images.githubusercontent.com/26769888/27510387-cf4389ae-592c-11e7-9111-ac28aa134124.jpg)

![screenshot 153 _li](https://user-images.githubusercontent.com/26769888/27510394-f2c6f618-592c-11e7-982b-33066c227d2f.jpg)

**Comment by arcticicestudio** [comment]
It seems like there is no way to change the line of the user settings.
I've changed the color of the separator line of the command bar (Quick Open) which is controlled by the `pickerGroup.border` selector.

**Comment by ajitid** [comment]
Can this be colored?
![capture](https://user-images.githubusercontent.com/26769888/27671023-90a1cbfe-5cae-11e7-9d7e-825f6b10825e.PNG)

**Comment by arcticicestudio** [comment]
🚢 Shipped with extension release version 🏷 [0.4.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.4.0).
