### ISSUE TITLE
Add more contrast to side panel active item

### ISSUE THREAD

**Issue by bmadone** [arcticicestudio/nord-visual-studio-code#246]
I think it would be better if the contrast for icons were brighter
![image](https://user-images.githubusercontent.com/23120972/176178975-9ea2f8a6-4f23-479e-bb8a-b75c31cd2571.png)

**Comment by fspoettel** [comment]
duplicate of https://github.com/arcticicestudio/nord-visual-studio-code/issues/156?

**Comment by fspoettel** [comment]
fwiw, you can try customizing this as [described here](https://www.nordtheme.com/docs/ports/visual-studio-code/customization).

I use this to get around the problem:

```js
  "workbench.colorCustomizations": {
    "[Nord]": {
      "list.activeSelectionIconForeground": "#2e3440",
    }
  }
```

**Comment by bmadone** [comment]
@fspoettel thanks, it just what I need
