### ISSUE TITLE
VS Code 1.13 workbench theme feature migration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-visual-studio-code#25]
[VS Code 1.13](https://code.visualstudio.com/updates/v1_13) has been released including a bunch of [new workbench theme features](https://code.visualstudio.com/updates/v1_13#_new-theming-colors) documented in the official [Theme Color Reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors).

#### [Base Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_base-colors)
  - [x] `errorForeground`

#### [Input Control](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_input-control)
  - [x] ` input.placeholderForeground`

#### [List and Trees](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_lists-and-trees)
  - [x] `list.inactiveSelectionForeground`
  - [x] `list.hoverForeground`
  - [x] `list.focusForeground`

#### [Sidebar](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_side-bar)
  - [x] `sideBar.foreground`
  - [x] `sideBar.border`
  - [x] `sideBarSectionHeader.foreground`

#### [Editor Groups & Tabs](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-groups-tabs)
  - [x] `editorGroupHeader.tabsBorder`
  - [x] `tab.unfocusedActiveForeground`
  - [x] `tab.unfocusedInactiveForeground`

#### Rulers
  - [x] `editorRuler.foreground`

#### Code Lens
  - [x] `editorCodeLens.foreground`

#### Bracket matches
  - [x] `editorBracketMatch.background`
  - [x] `editorBracketMatch.border`

#### Overview ruler
  - [x] `editorOverviewRuler.border`

#### Gutter
  - [x] `editorGutter.background`
  - [x] `editorGutter.modifiedBackground`
  - [x] `editorGutter.addedBackground`
  - [x] `editorGutter.deletedBackground`

### [Editor Widgets](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-widget-colors)
  - [x] `editorWidgetBorder`

#### [Peek View Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_peek-view-colors)
  - [x] `peekViewEditorGutter.background`

#### [Merge Conflicts](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_merge-conflicts)
  - [x] `merge.currentHeaderBackground`
  - [x] `merge.currentContentBackground`
  - [x] `merge.incomingHeaderBackground`
  - [x] `merge.incomingContentBackground`
  - [x] `merge.border`
  - [x] `editorOverviewRuler.currentContentForeground`
  - [x] `editorOverviewRuler.incomingContentForeground`

#### [Status Bar Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_status-bar-colors)
  - [x] `statusBar.debuggingForeground`
  - [x] `statusBar.noFolderForeground`
  - [x] `statusBar.noFolderBackground`
  - [x] `statusBar.border`

#### [Quick Picker](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_quick-picker)
  - [x] `pickerGroup.border`

#### [Integrated Terminal Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_integrated-terminal-colors)
  - [x] `terminal.background`
  - [x] `terminal.foreground`

#### [Welcome Page](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_welcome-page)
  - [x] `welcomePage.buttonBackground`
  - [x] `welcomePage.buttonHoverBackground`
  - [x] `walkThrough.embeddedEditorBackground`

**Comment by ajitid** [comment]
One suggestion: Just to keep theme minimal, please do not add `terminal.background` to it.

**Comment by arcticicestudio** [comment]
Currently the terminal uses the editor background color by default, `terminal.background` will be assigned to it too. Visually nothing will change, but the theme should include the selector just for completeness and to prevent side effects when the VS Code team decides to change the default values like they did to some settings in version 1.13.

**Comment by arcticicestudio** [comment]
🚢 Shipped with extension release version 🏷 [0.4.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.4.0).
