### ISSUE TITLE
Color function call and self in Python

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#26]
1. Function name in function call isn't colored in Python, while in other languages it is.
![capture](https://user-images.githubusercontent.com/26769888/27670894-a5800582-5cad-11e7-8b1a-74c3155e1ea2.PNG)
![capture](https://user-images.githubusercontent.com/26769888/27670925-d3d7d180-5cad-11e7-800f-c27cd5fe6b93.PNG)

1. `self` is not colored in function argument
![capture](https://user-images.githubusercontent.com/26769888/27670845-3884ce18-5cad-11e7-9be7-1967fb2f9d1f.PNG)

**Comment by arcticicestudio** [comment]
🚢 Shipped with extension release version 🏷 [0.4.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.4.0).
