### ISSUE TITLE
Double underlines under error and warnings

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#31]
Why are there double underlines under errror and warning in editor? I think only squiggle is more clean.

**Comment by arcticicestudio** [comment]
I've just added all new VS Code 1.13 workbench theme settings for completeness, but you're right that it looks a bit strange.
I'll remove the `editorError.border` in the next version or at least set the opacity to 0 just to prevent future default changes.

**Comment by ajitid** [comment]
@arcticicestudio Can we get 0.4.1 to fix this instead? Apart from https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#changes-for-extension-authors , I don't see any reason to release a new version soon. I wouldn't have asked for 0.4.1, but these error and warning underlines are something one would encounter quite a lot of time.

**Comment by arcticicestudio** [comment]
I'll prepare a fix version later this evening :wink:

**Comment by arcticicestudio** [comment]
Merged into :seedling:  `develop`.

<p align="center">Before<br><img src="https://user-images.githubusercontent.com/7836623/27764412-17801de2-5e99-11e7-9aa8-eabf39f30a75.png"/><br>After<br><img src="https://user-images.githubusercontent.com/7836623/27764413-1c29a516-5e99-11e7-917b-cabd827967ba.png"/></p>

**Comment by arcticicestudio** [comment]
🚢 Shipped with extension release version 🏷 [0.4.1](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.4.1).

**Comment by ajitid** [comment]
@arcticicestudio you did it in errors but missed it in warnings

**Comment by arcticicestudio** [comment]
Well, one reason you shouldn't code after some weekend drinks :laughing: 
Will prepare a fix version now.

**Comment by ajitid** [comment]
![capture](https://user-images.githubusercontent.com/26769888/27767300-c58e5ad0-5f10-11e7-9778-b4acf920d424.PNG)
Status bar is also not themed when no folder is active. Put this into your fix too. Thanks!

**Comment by arcticicestudio** [comment]
The status bar background has already been supported, but it got lost after a larger merge conflict I've solved for version 0.4.0. Will be solved in #32.

**Comment by arcticicestudio** [comment]
<p align="center">Before<br><img src="https://user-images.githubusercontent.com/7836623/27767496-818b5138-5ef9-11e7-80aa-4d4f03ec5856.png"/><br>After<br><img src="https://user-images.githubusercontent.com/7836623/27767497-8667f382-5ef9-11e7-9060-7f48106bd012.png"/></p>

**Comment by arcticicestudio** [comment]
🚢 Shipped with extension release version 🏷 [0.4.2](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.4.2).
