### ISSUE TITLE
VS Code 1.14

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#34]
VS Code 1.14 breaks heads-up notification label and button colors.

![screenshot 215](https://user-images.githubusercontent.com/26769888/28237654-27ddbc52-6962-11e7-9990-f1bb673107be.png)

New keys are here: https://github.com/Microsoft/vscode/issues/28280

Also 1.14 has introduced keyboard shortcuts as buttons in command palette, maybe there exist few keys for it too...

![screenshot 216](https://user-images.githubusercontent.com/26769888/28237669-9fbd9b7a-6962-11e7-804d-bc9347a14257.png)

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
I've also tracked the PR regarding the new notification button selectors and had already created a [backlog note card](https://github.com/arcticicestudio/nord-visual-studio-code/projects/2#card-3770138).

There are no selectors listed for the keyboard shortcut indicators in the [theme color reference guide](https://code.visualstudio.com/docs/getstarted/theme-color-reference), maybe this will be added to the next version.
