### ISSUE TITLE
Different contrast for sidebar and activity bar

### ISSUE THREAD

**Issue by imoby** [arcticicestudio/nord-visual-studio-code#35]
Any chance we can get different background color contrasts for the sidebar and the activity bar similar to the default theme?

**Comment by arcticicestudio** [comment]
The activity- and sidebar are designed flat to fit seamlessly with the surrounding UI, but you can customize it to fit your needs by using theme workbench overrides.

Open your `settings.json` by opening the command palette and search for *User Settings* or click on the gear icon in the activity bar and select *Settings*. Add the following keys to the workbench color customization object:

```json
"workbench.colorCustomizations": {
  "activityBar.background": "#3B4252",
  "sideBar.background": "#3B4252"
}
```

This will change the background color of the activity- and sidebar to *nord1*.

![gh-35-scrot-activity-bar](https://user-images.githubusercontent.com/7836623/29020447-4d809b8e-7b62-11e7-85b4-35b008d2e7f2.png)
![gh-35-scrot-sidebar](https://user-images.githubusercontent.com/7836623/29020448-4d82e786-7b62-11e7-9787-628b0d73ff64.png)

**Comment by imoby** [comment]
thanks. thats a good first start
