### ISSUE TITLE
Color setting for support.variable is missing

### ISSUE THREAD

**Issue by peterdanis** [arcticicestudio/nord-visual-studio-code#39]
In JS template literals support variables have the same color as strings. For TS setting is there but for JS it is missing.

    {
      "name": "[JavaScript] Variables",
      "scope": "source.js support.variable",
      "settings": {
        "foreground": "#D8DEE9"
      }
    }

Before:
![image](https://user-images.githubusercontent.com/26599181/29203022-b2d8b8a0-7e6d-11e7-96ea-f6cb32701e47.png)

After:
![image](https://user-images.githubusercontent.com/26599181/29203008-95b36518-7e6d-11e7-9a4a-df1b7edf94cd.png)

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 

I've created PR #51 which improves the string literal characters and the color of the variable properties.
