### ISSUE TITLE
Snap-in window is not visible

### ISSUE THREAD

**Issue by peterdanis** [arcticicestudio/nord-visual-studio-code#40]
Snap-in window is not visible while dragging it.

Change editorGroup.dropBackground to any other color than background color, with transparency. E.g.
"editorGroup.dropBackground": "#3b425299"

![image](https://user-images.githubusercontent.com/26599181/29203825-b4c27a06-7e73-11e7-9a0d-439383df42fb.png)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

I've pushed a fix for it.
