### ISSUE TITLE
CSS - Distinguish between tags and properties

### ISSUE THREAD

**Issue by peterdanis** [arcticicestudio/nord-visual-studio-code#52]
Hi,
please differentiate colors of tags (like `<a>` etc.) and properties (like `margin-bottom`)  in css.
Class and id targets use `nord7` (both in css and html) and tags use `nord9` (both in css and html), so I assume best would be to change the properties color. Please see the attached screenshot. Thanks.

![image](https://user-images.githubusercontent.com/26599181/30859273-419071ea-a2c3-11e7-921a-ce2cc310b602.png)

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 

I noticed that as well, it really hard to distinguish both tags and properties on larger selectors.
I've created PR #53 which changes properties to be colorized with `nord4`.
