### ISSUE TITLE
Push 0.6.0 update

### ISSUE THREAD

**Issue by ajitid** [arcticicestudio/nord-visual-studio-code#54]

**Comment by arcticicestudio** [comment]
Please don't open up issues for such topics, it messes up the issue management and increases the maintainability effort. There are many other channels like Twitter or Email for such things :smile:

**Comment by ajitid** [comment]
Sorry!

**Comment by ajitid** [comment]
Never saw you replying on Twitter arcticicestudio handle, so thought that you only make announcements there. Again sorry for disturbing you.

**Comment by arcticicestudio** [comment]
I use Twitter as my main communication tool, but I don't reply to `@` mentions every time because most users are in a discussion about e.g. which theme they use and only wanted to link to the theme. Otherwise I almost reply instantly since Tweetdeck is open 24/7 on my system :laughing:
