### ISSUE TITLE
Update to new 1.14 constraints for rendering SVG images

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-visual-studio-code#55]
Due to security concerns, [VS Code version 1.14 introduced a change so SVG images are no more rendered within VS Code][rn] with the following contraints:

* The icon provided in *package.json* may not be an SVG.
* The badges provided in the *package.json* may not be SVGs unless they are from [approved badge providers][abp].
* Image URLs in `README.md` and `CHANGELOG.md` need to resolve to https URLs.
* Images in `README.md` and `CHANGELOG.md` may not be SVGs unless they are from [approved badge providers][abp].
* Images in `README.md` and `CHANGELOG.md` may not use data URIs.

![gh-55-scrot-broken-svg-rendering](https://user-images.githubusercontent.com/7836623/31324602-9f40d5be-acb4-11e7-88b3-f86cf6cdacf1.png)

### Tasks

* [ ] Convert the `package.json` marketplace icon to PNG (*x2*).
* [ ] Convert project banner to PNG (*x2*).

[abp]: https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_approved-badges
[rn]: https://code.visualstudio.com/updates/v1_14#_extension-authoring

**Comment by kushalpandya** [comment]
I can take this up. :slightly_smiling_face:
