### ISSUE TITLE
Comment text is not very visible in added diff view

### ISSUE THREAD

**Issue by octref** [arcticicestudio/nord-visual-studio-code#61]
![image](https://user-images.githubusercontent.com/4033249/33282870-dd45ea86-d35e-11e7-8a10-e832d1c5d7d0.png)

If this cannot be solved by changing some values in the existing schema, I can also open an issue on VS Code side to request a theme config for this case.

**Comment by arcticicestudio** [comment]
I don't know any scope that could be used to adjust the comment color when shown in the diff view so unfortunately this is a edge case when using a [customized brighter comment color][ref]. Using the default theme comment color works fine.

![gh-61-default-theme-comment color](https://user-images.githubusercontent.com/7836623/33512929-2a37e94c-d739-11e7-9a32-9ee39a79dc81.png)

[ref]: https://github.com/arcticicestudio/nord-visual-studio-code/issues/14#issuecomment-315541716

**Comment by octref** [comment]
Just tried it, the default comment contrast is enough for me so I removed the customized comment color. Thanks!
