### ISSUE TITLE
New tab mouse hover and border styles

### ISSUE THREAD

**Issue by OfficerHalf** [arcticicestudio/nord-visual-studio-code#66]
There are some new themable color options nord *could* support, though it's certainly not necessary. The new colors are:
```
tab.hoverBackground
tab.hoverBorder
tab.unfocusedHoverBackground
tab.unfocusedHoverBorder
```

I have mine set like this
```
"workbench.colorCustomizations": {
        "tab.hoverBackground": "#434c5e",
        "tab.hoverBorder": "#d08770",
        "tab.unfocusedHoverBorder": "#88c0d0"
}
```

**Comment by arcticicestudio** [comment]
Thanks for your help, I've quickly read over the release notes of version 1.20 some days ago and already added a [note card][card] for the new theme keys.

[card]: https://github.com/arcticicestudio/nord-visual-studio-code/projects/2#card-7462441

**Comment by arcticicestudio** [comment]
The new keys have been added and can be tested in PR #89.
