### ISSUE TITLE
Highlighted indent guides

### ISSUE THREAD

**Issue by gulshan** [arcticicestudio/nord-visual-studio-code#69]
Please provide a value for newly introduced `editorIndentGuide.activeBackground` to differentiate active indent guide from other indent guides (`editorIndentGuide.background`).

**Comment by OfficerHalf** [comment]
Even something slightly lighter (I have mine set to #5e6474b3) would work.

![image](https://user-images.githubusercontent.com/4851889/39759293-f0afc476-5297-11e8-8c38-adc19aa9ed48.png)

**Comment by bgarrant** [comment]
Please add this feature.  Nord is awesome and highlighted indent guide helps a lot.

**Comment by arcticicestudio** [comment]
Introduced in VS Code v1.23 for [highlighted indent guides][rn].

<p align="center"><img src="https://code.visualstudio.com/assets/updates/1_23/active-indent-guide.gif" /></p>

[rn]: https://code.visualstudio.com/updates/v1_23#_highlighted-indent-guides

**Comment by bgarrant** [comment]
Has this been added?

**Comment by arcticicestudio** [comment]
@bgarrant It is planned for the next release version [0.7.0][]. You can see the progress on the [project board][pb] for this version

[0.7.0]: https://github.com/arcticicestudio/nord-visual-studio-code/milestone/10
[pb]: https://github.com/arcticicestudio/nord-visual-studio-code/projects/12#card-10879662

**Comment by bgarrant** [comment]
Thanks so much.  We love Nord!

**Comment by arcticicestudio** [comment]
The new keys have been added and can be tested in PR #90.
