### ISSUE TITLE
Doesn't highlight Go string format placeholders

### ISSUE THREAD

**Issue by jsvensson** [arcticicestudio/nord-visual-studio-code#7]
Version: Nord 0.1.1

The Nord theme is missing colors for `constant.other.placeholder.go`, which golang uses for Printf (etc) placeholders.

![clipboard02](https://cloud.githubusercontent.com/assets/450287/24587296/0b1a7b5a-17b4-11e7-926d-586c11b3ccee.png)

Example of the Solarized theme with the same line of Go code:

![clipboard01](https://cloud.githubusercontent.com/assets/450287/24587297/15304ea8-17b4-11e7-9c42-4b86b39c19a1.png)

I don't really know my way around the theme, but I did a quick test using the escape character color:

![clipboard01](https://cloud.githubusercontent.com/assets/450287/24587401/ffa90f14-17b5-11e7-9546-72a4d021eb0f.png)

``` xml
<dict>
    <key>name</key>
    <string>[Go] String format placeholder</string>
    <key>scope</key>
    <string>source.go constant.other.placeholder.go</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#EBCB8B</string>
    </dict>
</dict>
```

Good job on this color scheme, definitely one of my favorites!

**Comment by arcticicestudio** [comment]
![ghi-7-scrot-after](https://cloud.githubusercontent.com/assets/7836623/24760013/a12bb286-1ae7-11e7-9a4a-f3c745e2c497.png)

**Comment by jsvensson** [comment]
It seems this change didn't make it into the switch from the tmTheme format to the JSON file.

**Comment by arcticicestudio** [comment]
I've used the builtin converter provided by VS Code to migrate to the new JSON format.
It seems like there have been some problems which are described in #12.
