### ISSUE TITLE
Incorrect installation instructions

### ISSUE THREAD

**Issue by kballard** [arcticicestudio/nord-visual-studio-code#70]
The installation instructions should say to run `ext install arcticicestudio.nord-visual-studio-code`. The current instructions just searches the marketplace for the string `nord-visual-studio-code`, which doesn't actually even find the theme.

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 
It'll be fixed and published to the registry with the next release version.

**Comment by arcticicestudio** [comment]
Sorry for the delay, I've had no free time (job :man_health_worker:, study :book:, life :weight_lifting_man: etc.) to work on my or any other :octocat: OSS project (see Tweets :bird: from [April][t-april] and [June][t-june]), but from the beginning of July I finished my studies and can [finally spend time on OSS again][t-back] :green_heart:

[t-april]: https://twitter.com/arcticicestudio/status/987753414342914049
[t-june]: https://twitter.com/arcticicestudio/status/1004777280646844417
[t-back]: https://twitter.com/arcticicestudio/status/1010013091793256448
