### ISSUE TITLE
Markdown blockquote text is too dark

### ISSUE THREAD

**Issue by OfficerHalf** [arcticicestudio/nord-visual-studio-code#72]
Perhaps not constrasting enough is a more accurate description. A better color should be selected. Perhaps to differentiate it from other text, it could be made italic? For now I've just set it to the same color as my comments, which I have at `#66738e`.

![capture70](https://user-images.githubusercontent.com/4851889/40922765-a36c1b50-67d8-11e8-91cf-a73e52e1b1f6.PNG)

This is `text.html.markdown markup.quote`.

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

This is related to #14 and the resulting arcticicestudio/nord#94 . When both issues have been resolved/implemented this will also be applied to quotes in Markdown since these are a main element of the Markdown syntax. You can use a scoped customization like described by a user in #14.

**Comment by arcticicestudio** [comment]
Hi @OfficerHalf :wave: again

Its finally time to close this long-time issue :tada: 

PR #118 (implementing https://github.com/arcticicestudio/nord/issues/94 through #117) has been merged and version [0.8.0][] has been release and deployed to the VS Code Marketplace :rocket:

The comment's color brightness (`nord3`) is now increased by 10% from a lightness level of ~35% to ~45%.

Feel free to let me know what you think about this change!
➜ Please see https://github.com/arcticicestudio/nord/issues/94 for all details about this design change decision.

#### Before

![gh-146-before](https://user-images.githubusercontent.com/7836623/54902736-76886c80-4eda-11e9-86cd-dfc935aff5e3.png)
![gh-145-before-2](https://user-images.githubusercontent.com/7836623/54902735-76886c80-4eda-11e9-9aa0-41ded647bdb2.png)

#### After

![gh-146-preview](https://user-images.githubusercontent.com/7836623/54902766-856f1f00-4eda-11e9-897a-9b0971586a0b.png)
![gh-145-preview-2](https://user-images.githubusercontent.com/7836623/54902765-856f1f00-4eda-11e9-9d09-50c89faece43.png)

[0.8.0]: https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.8.0
