### ISSUE TITLE
Can not move tab

### ISSUE THREAD

**Issue by sdr0x07b6** [arcticicestudio/nord-visual-studio-code#98]
Can not move tab

1. Editor split. For example, top and bottom.
2. Drag a tab and move it to another area. For example, from top to bottom.
3. Can not... All the other themes can do it.

Moving "from bottom to top" and "left and right" movements are only possible for the first time you enter the drag area for the first time.
"Top to bottom" can not be done at all.

- Nord Visual Studio Code v0.6.0
- VS Code 1.26.0
- macOS 10.13.6

**Comment by arcticicestudio** [comment]
Hi @sdr0x07b6 :wave:, thanks for your contribution. Sorry for the long delay, I've been really busy with my job, real life and [Nord's, finally launched, official website and documentation](https://www.nordtheme.com).

@mdogadailo submitted PR #98 to fix the problem. I've merged it to deploy it with the next release version :rocket:
