### ISSUE TITLE
Highlighting too bright and buries text

### ISSUE THREAD

**Issue by octref** [arcticicestudio/nord-visual-studio-code#99]
Active keybinding in keyboard shortcut editor:

![image](https://user-images.githubusercontent.com/4033249/44305892-a8c85f00-a338-11e8-9db5-a52a5b4d8f9c.png)

Peek definition:

![image](https://user-images.githubusercontent.com/4033249/44305931-3e63ee80-a339-11e8-91e3-ad40ccbbe98e.png)

**Comment by kapiljaveri** [comment]
Hello

Would the following changes work for you? If so, I can submit a PR.

![keyboard-shortcuts](https://user-images.githubusercontent.com/6692991/46516304-9a71cc00-c82e-11e8-979f-4bff5434c648.png)

![command-palette](https://user-images.githubusercontent.com/6692991/46516310-9fcf1680-c82e-11e8-9e26-d97f7d89c7de.png)

![peek-view](https://user-images.githubusercontent.com/6692991/46516312-a3629d80-c82e-11e8-873a-8a8a05f0da52.png)

**Comment by arcticicestudio** [comment]
Sorry for the stale state.

@octref Is it still required to adjust the background color for a list selection? It looks like VS Code has been updated and the foreground color of the mapped keys are now colorized in black automatically.

![gh-99-list-selection-bg](https://user-images.githubusercontent.com/7836623/54864867-7ca50e80-4d5d-11e9-834b-fda693094e64.png)

We could decrease the opacity to 80%, but in my opinion this will also decrease the readability of the text (dark text on dark background).

The match highlighting of the peek view is indeed to bright and reducing it's opacity to 30% should work fine.

![gh-99-peek-view](https://user-images.githubusercontent.com/7836623/54864866-76af2d80-4d5d-11e9-9800-37fb5c7e10dc.png)
